# Generated by Django 3.0.2 on 2020-03-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(null=True, verbose_name='question')),
                ('choice1', models.TextField(null=True, verbose_name='choice1')),
                ('choice2', models.TextField(null=True, verbose_name='choice2')),
                ('choice3', models.TextField(null=True, verbose_name='choice3')),
                ('choice4', models.TextField(null=True, verbose_name='choice4')),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200, null=True, verbose_name='description')),
            ],
        ),
    ]
