# Generated by Django 3.0.2 on 2020-03-13 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_question_quiz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
